Golangci-lint update (nilerr linter)
internal/controller/postgrescluster/patroni.go:274:4: error is nil but it returns error (nilerr)
                        return custom, err
                        ^
internal/controller/postgrescluster/patroni.go:334:3: error is nil but it returns error (nilerr)
                return intent, err